create table person
(
    id integer not null,
    name varchar(255) not null,
    location varchar(255),
    birthdate timestamp
);

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE) VALUES (10000, 'MARK', 'ENGLAND', SYSDATE());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE) VALUES (10001, 'GREG', 'ENGLAND', SYSDATE());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE) VALUES (10002, 'CRAIN', 'ENGLAND', SYSDATE());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE) VALUES (10003, 'SCOT', 'ENGLAND', SYSDATE());